services:
  docs:
    image: be_logbook_local_docs
    container_name: be_logbook_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - path: ./.envs/.local/.django
        required: false
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./be_logbook:/app/be_logbook:z
    ports:
      - '9000:9000'
    command: /start-docs
