# Generated by Django 5.2.16 on 2026-08-26 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CHANGES_REQUIRED', 'Changes Required'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.academicyear')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_groups', to='workflow.stage')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.department')),
            ],
            options={
                'verbose_name': 'Project Group',
                'verbose_name_plural': 'Project Groups',
                'ordering': ['academic_year', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='GuideAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for (re)assignment / reassignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_assignments', to='groups.projectgroup')),
            ],
            options={
                'verbose_name': 'Guide Assignment',
                'verbose_name_plural': 'Guide Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('designation', models.CharField(blank=True, help_text='e.g. Team Lead, Member', max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.projectgroup')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['group', 'join_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectgroup',
            constraint=models.UniqueConstraint(fields=('academic_year', 'group_number'), name='uniq_group_number_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='guideassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group',), name='uniq_active_guide_per_group'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('group', 'student'), name='uniq_active_membership_per_group'),
        ),
    ]
