# Generated by Django 5.2.16 on 2026-08-26 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('groups', '0001_initial'),
        ('submissions', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reassignment reason if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='groups.projectgroup')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to='workflow.stage')),
            ],
            options={
                'verbose_name': 'Review Assignment',
                'verbose_name_plural': 'Review Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FINALIZED', 'Finalized'), ('CORRECTION_REQUESTED', 'Correction Requested'), ('CORRECTED', 'Corrected')], default='DRAFT', max_length=20)),
                ('total_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='groups.projectgroup')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='assessments.rubric')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='workflow.stage')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.reviewassignment')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='assessments.rubriccriterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review Mark',
                'verbose_name_plural': 'Review Marks',
            },
        ),
        migrations.CreateModel(
            name='ReviewMarkCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_obtained', models.DecimalField(decimal_places=2, max_digits=8)),
                ('new_obtained', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_corrections', to='submissions.approval')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_corrections', to='reviews.review')),
                ('review_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='reviews.reviewmark')),
            ],
            options={
                'verbose_name': 'Review Mark Correction',
                'verbose_name_plural': 'Review Mark Corrections',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'stage'), name='uniq_active_reviewer_per_group_stage'),
        ),
        migrations.AddConstraint(
            model_name='reviewmark',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='uniq_review_criterion_mark'),
        ),
    ]
