# Generated by Django 5.2.16 on 2026-08-26 18:39

import be_logbook.logbook.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to=be_logbook.logbook.models._logbook_path)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logbooks_generated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Generated Log Book',
                'verbose_name_plural': 'Generated Log Books',
                'ordering': ['-generated_at'],
            },
        ),
    ]
