# Generated by Django 5.2.16 on 2026-08-26 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=60)),
                ('entity', models.CharField(max_length=60)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_state', models.TextField(blank=True, null=True)),
                ('new_state', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'object_id'], name='audit_audit_entity_5915e1_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
