# Generated by Django 5.2.16 on 2026-08-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('guide_approval_required', models.BooleanField(default=True)),
                ('reviewer_approval_required', models.BooleanField(default=False)),
                ('document_required', models.BooleanField(default=False)),
                ('marks_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('PROJECT_INFO', 'Project & Group Information'), ('GROUP_INFO', 'Group Information'), ('STUDENT_INFO', 'Student Information'), ('SCHEDULE', 'Project Schedule'), ('TOPIC_FINALIZATION', 'Topic Finalization'), ('MONTHLY_ACTIVITY', 'Monthly Activity Charts'), ('RTM', 'Requirement Traceability Matrix'), ('COST_ESTIMATION', 'Cost Estimation'), ('UML_DESIGN', 'UML / Design'), ('REVIEWS', 'Reviews'), ('COMPETITION', 'Competition Details'), ('PUBLICATION', 'Paper Publication Details'), ('TERM_I', 'Term-I'), ('TERM_II', 'Term-II'), ('FINAL_SUBMISSION', 'Final Submission'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workflow.stage')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['stage', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='StageDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_deadlines', to='academics.academicyear')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='workflow.stage')),
            ],
            options={
                'verbose_name': 'Stage Deadline',
                'verbose_name_plural': 'Stage Deadlines',
                'unique_together': {('stage', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StageDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='workflow.stage')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflow.stage')),
            ],
            options={
                'verbose_name': 'Stage Dependency',
                'verbose_name_plural': 'Stage Dependencies',
                'unique_together': {('stage', 'depends_on')},
            },
        ),
    ]
