# Generated by Django 5.2.16 on 2026-08-26 18:39

import be_logbook.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=be_logbook.documents.models._doc_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['document', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PHOTO', 'Student Photograph'), ('SYNOPSIS', 'Synopsis'), ('REPORT', 'Project Report'), ('UML', 'UML Diagram'), ('PAPER', 'Research Paper'), ('CERTIFICATE', 'Certificate'), ('COMPETITION_CERT', 'Competition Certificate'), ('SPONSORSHIP', 'Sponsorship / Completion Letter'), ('PPT', 'Presentation (PPT)'), ('CODE', 'Code / Archive'), ('OTHER', 'Other')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=be_logbook.documents.models._doc_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPLACED', 'Replaced'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.projectgroup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
