# Generated by Django 5.2.16 on 2026-08-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('program', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Outcome',
                'verbose_name_plural': 'Program Outcomes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='COPOAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_code', models.CharField(blank=True, max_length=20)),
                ('po_code', models.CharField(blank=True, max_length=20)),
                ('attainment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copo', to='groups.projectgroup')),
            ],
            options={
                'verbose_name': 'CO/PO Attainment',
                'verbose_name_plural': 'CO/PO Attainments',
                'ordering': ['group', 'co_code', 'po_code'],
            },
        ),
    ]
